config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, only: [:new]
    resource :friendships, only: [:create, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :secrets, only: [:create]


  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id
  validate :no_self_friendship
  validate :no_duplicates
  validates :in_friend_id, :out_friend_id, presence: true

  belongs_to(
  :out_friend,
  class_name: "User",
  foreign_key: :out_friend_id,
  primary_key: :id
  )

  belongs_to(
  :in_friend,
  class_name: "User",
  foreign_key: :in_friend_id,
  primary_key: :id
  )

  def self.can_friend?(out_friend_id, in_friend_id)
    !Friendship.exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id) &&
    in_friend_id != out_friend_id
  end

  private
    def no_self_friendship
      if self.in_friend_id == self.out_friend_id
        errors[:friendship] << "can't friend yourself"
      end
    end

    def no_duplicates
      unless Friendship.can_friend?(self.out_friend_id, self.in_friend_id)
        errors[:friendship] << "can't duplicate friendship"
      end
    end

end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :tag_id, :secret_id

  belongs_to(:secret)
  belongs_to(:tag)

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many(:secret_taggings)
  has_many :secrets, through: :secret_taggings, source: :secret

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
  :out_friendships,
  class_name: "Friendship",
  foreign_key: :out_friend_id,
  primary_key: :id
  )

  has_many(
  :in_friendships,
  class_name: "Friendship",
  foreign_key: :in_friend_id,
  primary_key: :id
  )

  has_many :out_friends, through: :in_friendships, source: :out_friend
  has_many :in_friends, through: :out_friendships, source: :in_friend


  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = Friendship.new(in_friend_id: current_user.id, out_friend_id: params[:user_id])
    @friendship.save!
    head :ok
    #redirect_to users_url
  end

  def destroy
    @friendship = Friendship.find_by_in_friend_id_and_out_friend_id(
                                                    current_user.id,
                                                    params[:user_id])


    @friendship.destroy
    head :ok
    #redirect_to users_url
  end


end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def create
    params[:secret][:author_id] = current_user.id
    @secret = Secret.new(params[:secret])

    if @secret.save
      head :ok
    else
      render :json => @secret.errors.full_messages
    end
  end


  def new
    @users = User.where("id != ?", current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    @users = current_user.out_friends
    @tags = Tag.all
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.where("id != ?", current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form class="secret-form" action="<%= secrets_url %>" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     <!-- we should have @user here instead of the dropdown
     so you have to go to a particular user's show page
     to post a secret to them -->
     <select name="secret[recipient_id]">
       <% @users.each do |user| %>
         <option value="<%= user.id %>"><%= user.username %></option>
       <% end %>
       </select>
     Secret:<input type="text" name="secret[title]">
     <div id="select-div"></div>
     <%#= render partial: "secrets/tag" %>
     <a id="add-tag" href="">Add another Tag</a>
     <input id="create-secret" type="submit" value="Create Secret!">
</form>

<script type="application/json" id="tag-json">
{ "tags": <%= Tag.all.to_json.html_safe %> }

</script>

<script type="text/template" id="tags_template">
  <select name="secret[recipient_id]">
  <%% _.each(tags, function(tag){ %>
    <option value="<%%= tag.id %>"><%%= tag.name %></option>
    <%% }); %>
  </select>
</script>

<script>
  var data = JSON.parse($("#tag-json").html());
  var addSecretTagSelect = function(){
    var templateCode = $("#tags_template").html();
    var templateFn = _.template(templateCode);
    var renderedContent = templateFn(data);
    $("#select-div").html(renderedContent);
  };
</script>

<script>
$(function(){
  addSecretTagSelect();
  $('#add-tag').on("click", function(event) {
    event.preventDefault();
    event.stopPropagation();
     addSecretTagSelect();
  //$(".secret-form").append($('#clonable').clone()); //$('input[name="secret_tags[]"]').after($('input[name="secret_tags[]"]').clone())
  });
});
</script>

app/views/secrets/_tag.html.erb
Tag: <select id="clonable" name="secret_tags[]">
  <% @tags.each do |tag| %>
  <option value="<%= tag.id %>"><%= tag.name %></option>
  <% end %>
</select>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/_user.html.erb
<li><%= user.username %>
  <% if Friendship.can_friend?(user.id, current_user.id) %>
  <%= button_to "Add Friend", user_friendships_url(user) %>
  <% end %>

</li>

app/views/users/index.html.erb
<h1>User Index</h1>

<!-- <ul>
  <%= render @users %>
</ul> -->



<!-- rewrite in javascript for practice -->
<div id="friends">
  <% @users.each do |user| %>
  <% klass = Friendship.can_friend?(user.id, current_user.id) ? "can-friend" : "can-unfriend" %>
  <span class="friend-buttons <%= klass %>">
    <%= user.username %>

      <button class="friend" out-user-id="<%= user.id %>">Add Friend</button>
      <button class="unfriend" out-user-id="<%= user.id %>">Remove Friend</button>
      <%#= button_to "Delete friend", user_friendships_url(user), method: :delete %>
  </span>
  <% end %>
</div>

<script type="text/javascript">
  function toggleFriendButtons(){
    console.log(this);
    var $friendButtons = this.parent();
    if ($friendButtons.hasClass("can-friend")){
      $friendButtons.removeClass("can-friend");
      $friendButtons.addClass("can-unfriend");
    } else {
      $friendButtons.removeClass("can-unfriend");
      $friendButtons.addClass("can-friend");
    };
  };
  $(function(){
    $(".friend-buttons").on("click", ".friend", function(event){
      var $friend = $(event.currentTarget);
      $friend.text("friending...").attr("disabled","disabled");
      var outUserId = parseInt($friend.attr("out-user-id"));
      $.ajax({
        url: "/users/" + outUserId + "/friendships",
        type: "POST",
        data: { //controller will have other user's id
        },
        success: function() {
          toggleFriendButtons.bind($friend)();
          $friend.text("Add Friend").removeAttr("disabled");
          //$friend.toggleFriendButtons();
          //$friend.remove();
        },
        errors: function() {
          alert("error creating friendship")
        }

      });
      //alert("you clicked on id " + userId);
    });
    $(".friend-buttons").on("click", ".unfriend", function(event){
      var $unFriend = $(event.currentTarget);
      $unFriend.text("unfriending...").attr("disabled","disabled");
      var outUserId = parseInt($unFriend.attr("out-user-id"));
      $.ajax({
        url: "/users/" + outUserId + "/friendships",
        type: "DELETE",
        data: { //controller will have other user's id
        },
        success: function() {
          toggleFriendButtons.bind($unFriend)();
          $unFriend.text("Remove Friend").removeAttr("disabled");
          //$unFriend.toggleFriendButtons();
          //$unFriend.remove();
        },
        errors: function() {
          alert("error deleting friendship")
        }

      });
      //alert("you clicked on id " + userId);
    });
  });
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul>
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

<h2>New Secret</h2>

<!-- this should be conditional only if the logged in user is not on there own page -->
<%= render partial: "secrets/form" %>

<script>
  $(function(){
    $('.secret-form').on("submit", function(event){
      event.preventDefault();
      var secretTitle = $('input[name="secret[title]"]').val();//?could be .text
      var formData = $(this).serialize();
      $.ajax({
        url: "/secrets",
        type: "POST",
        data: formData,
        success: function(){
          $('.secret-form')[0].reset();
          $("ul").append("<li>" + secretTitle + "</li>");
        }
      });
    });
  });

</script>